services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedbackdb
    volumes:
      - feedback-app-data:/var/lib/postgresql/data
    networks:
      - feedback-app-nw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  feedback_app:
    image: galaataman/feedback-app:latest
    container_name: feedback-app
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres-db
      - DB_NAME=feedbackdb
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - feedback-app-nw
    ports:
      - "3030:3000"
    depends_on:
      postgres_db:
        condition: service_healthy

  feedback_app_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_HOST=localhost
        - REACT_APP_BACKEND_PORT=3030
    container_name: feedback-app-frontend
    networks:
      - feedback-app-nw
    ports:
      - "80:80"
    depends_on:
      - feedback_app

networks:
  feedback-app-nw:
    driver: bridge

volumes:
  feedback-app-data: