version: '3.8'

services:
  frontend:
    build:
      context: ./feedback-app-frontend
    environment:
      - FEEDBACK_BACKEND_HOST=backend
      - FEEDBACK_BACKEND_PORT=5000
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./feedback-app:/app
    command: sh -c "yarn install && yarn start"
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresq1/data

volumes:
  db-data: